name: Run Calkit
description: >
  Run a Calkit project pipeline and optionally commit and push results to
  Git and DVC remotes.
branding:
  icon: arrow-right
  color: green
inputs:
  save:
    description: Whether or not to save (commit and push) results to Git and DVC remotes.
    default: "true"
  dvc_token:
    description: DVC token for pushing results. If not provided, will be obtained via GitHub OIDC.
    required: false
  pull_dvc:
    description: Whether or not to pull DVC data before running.
    required: false
    default: "true"
  cache_dvc:
    description: Whether or not to cache DVC data.
    required: false
    default: "true"
  run_args:
    description: Arguments passed to calkit run command.
    required: false
    default: ""
outputs: {}
runs:
  using: composite
  steps:
    - name: Restore DVC cache
      if: ${{ inputs.cache_dvc == 'true' }}
      id: cache-dvc-restore
      uses: actions/cache/restore@v4
      with:
        path: .dvc/cache
        key: ${{ runner.os }}-dvc-cache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-dvc-cache-
    - name: Get GitHub OIDC token
      if: ${{ !inputs.dvc_token && (inputs.save == 'true' || inputs.pull_dvc == 'true') }}
      id: get-oidc-token
      shell: bash
      run: |
        OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=calkit.io" -s | jq -r '.value')
        if [ -z "$OIDC_TOKEN" ] || [ "$OIDC_TOKEN" == "null" ]; then
          echo "Failed to obtain OIDC token"
          exit 1
        fi
        echo "::add-mask::$OIDC_TOKEN"
        echo "oidc-token=$OIDC_TOKEN" >> $GITHUB_OUTPUT
    - name: Exchange OIDC token for Calkit DVC token
      if: ${{ !inputs.dvc_token && (inputs.save == 'true' || inputs.pull_dvc == 'true') }}
      id: get-dvc-token
      shell: bash
      run: |
        CALKIT_DVC_TOKEN=$(curl -X POST https://api.calkit.io/login/github-oidc \
          -H "Authorization: Bearer ${{ steps.get-oidc-token.outputs.oidc-token }}" \
          -s | jq -r '.access_token')
        if [ -z "$CALKIT_DVC_TOKEN" ] || [ "$CALKIT_DVC_TOKEN" == "null" ]; then
          echo "Failed to obtain Calkit DVC token"
          exit 1
        fi
        echo "::add-mask::$CALKIT_DVC_TOKEN"
        echo "dvc-token=$CALKIT_DVC_TOKEN" >> $GITHUB_OUTPUT
    - run: calkit config remote-auth
      if: ${{ inputs.save == 'true' || inputs.pull_dvc == 'true' }}
      shell: bash
      env:
        CALKIT_DVC_TOKEN: ${{ inputs.dvc_token || steps.get-dvc-token.outputs.dvc-token }}
    - run: calkit dvc pull
      if: ${{ inputs.pull_dvc == 'true' }}
      shell: bash
      continue-on-error: true
    - run: calkit run ${{ inputs.run_args }}
      shell: bash
    - run: calkit save -am "Run pipeline"
      if: ${{ inputs.save == 'true' }}
      shell: bash
      env:
        CALKIT_DVC_TOKEN: ${{ inputs.dvc_token || steps.get-dvc-token.outputs.dvc-token }}
    - name: Save DVC cache
      if: ${{ inputs.cache_dvc == 'true' }}
      id: cache-dvc-save
      uses: actions/cache/save@v4
      with:
        path: .dvc/cache
        key: ${{ runner.os }}-dvc-cache-${{ github.sha }}
